export const events = [
	{
		id: "001",
        name: "1 Event",
        description: "During Kaunas Old Town tour you will be introduced in rich history and culture of one of the oldest cities in Lithuania. Kaunas Old Town is full of magnificent different architectural styles buildings from XIV to XVIII ages.",
		checkpointCount: "3",
		checkpoints: [],
		teamSize: "4",
		teams: [],
		createdDate: "9-12-1900",
        eventStatus: "Open",	
	}, {
		id: "002",
		name: "2 Event",
        description: "During “Tsarist Kaunas” tour you will be introduced into history of the city during the 19th century when Lithuania was part of Russian Empire. You will learn how Kaunas was expanded during tsarist times and what influence Kaunas had to all Russian Empire.",
		checkpointCount: "8",
		checkpoints: [],
		teamSize: "4",
		teams: [],
		createdDate: "8-12-2019",
		eventStatus: "In progress",	
	}, {
		id: "003",
		name: "3 Event",
        description: "Kaunas New Town is one of the most magnificent places in the city. Today many people even don’t know that New Town was planned and built by Russian Empire. From the middle of 19th century until World War I Kaunas City expanded rapidly.",
		checkpointCount: "6",
		checkpoints: [],
		teamSize: "2",
		teams: [],
		createdDate: "7-12-2019",
		eventStatus: "Open",	
	}, {
		id: "004",
		name: "4 Event",
        description: "Get off the tourist trail and see the real Vilnius with a local! This 2-hour walking tour takes you through several different districts where present-day life meets the past. ",
		checkpointCount: "4",
		checkpoints: [],
		teamSize: "1",
		teams: [],
		createdDate: "6-12-2019",
		eventStatus: "Closed",	
	}, {
		id: "005",
		name: "5 Event",
        description: "Forget churches and tourist brochure pictures, explore the neighborhoods that were not made for tourists and discover expanding alternative culture. This is our local Brooklyn, Kreuzberg and Friedrichschain – new vibe constructed on ex-industrial concrete that remembers soviet times. ",
		checkpointCount: "7",
		checkpoints: [],
		teamSize: "2",
		teams: [],
		createdDate: "5-12-2019",
		eventStatus: "In progress",	
	}, {
		id: "006",
		name: "6 Event",
        description: "Join our classic walking tour and explore Vilnius' magical medieval Old Town with a qualified local guide. Visit famous sights and hidden corners while enjoying entertaining tales of the city’s history and its people. ",
		checkpointCount: "9",
		checkpoints: [],
		teamSize: "5",
		teams: [],
		createdDate: "4-12-2019",
		eventStatus: "Closed",	
	}, {
		id: "007",
		name: "7 Event",
        description: "Visit Vilnius’ key Soviet heritage sites, see a different side of the city, find out how the Soviet occupation impacted local life and hear funny and crazy stories that should never be forgotten.",
		checkpointCount: "10",
		checkpoints: [],
		teamSize: "5",
		teams: [],
		createdDate: "3-12-2019",
		eventStatus: "In progress",	
	}, {
		id: "008",
		name: "8 Event",
        description: "Discover all the highlights of Curonian Spit National Park with drifting sand dunes, pine forests, elks and fine beaches, plus a professional local guide on this private day trip from Klaipeda.",
		checkpointCount: "5",
		checkpoints: [],
		teamSize: "4",
		teams: [],
		createdDate: "2-12-2019",
		eventStatus: "Closed",	
	}, {
		id: "009",
		name: "9 Event",
        description: "Visit one of the oldest cities in Lithuania. Discover its charming Old Town, beautiful Baltic Sea location and mix of cultures. ",
		checkpointCount: "3",
		checkpoints: [],
		teamSize: "1",
		teams: [],
		createdDate: "1-12-2019",
		eventStatus: "Open",	
	},  
]